[package]
name = "arcane-http"
version = "0.1.0"
authors = ["Stephen Lecrenski <slecrenski@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
